
name: 'Setup OIDC AWS profile'
description: 'Gets a GH token and uses it to setup an AWS profile with OIDC'
inputs:
  role-to-assume:
    description: 'The arn of the role to assume'
    required: true
  role-session-name:
    description: 'The name of the session'
    required: true
  aws-region:
    description: 'The AWS region to use'
    required: true
  profile:
    description: 'The name of the profile to create'
    required: true
  session-duration:
    description: 'The duration of the session in seconds'
    required: false
    default: '3600'
runs:
  using: 'node20'
  main: 'dist/index.js'
